exclude:
#Config files
- /BenChain.Api/BenChain.Api/App_Start/SwaggerConfig.cs
- /BenChain.Api/BenChain.Api/App_Start/WebApiConfig.cs
- /BenChainClient.Api/BenChainClient.Api/BenChainClient.Api/App_Start/SwaggerConfig.cs
- /BenChainClient.Api/BenChainClient.Api/BenChainClient.Api/App_Start/WebApiConfig.cs